controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /home
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\HomepageController::index

app_login:
    path: /login
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\LoginController::login

app_logout:
    path: /logout
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\LoginController::logout

app_register:
    path: /register
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\RegistrationController::register

app_verify_email:
    path: /verify/email
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\LoginController::verify/email



